export default {
  primaryColor: "#666CE4",
  backgroundColor: "#F5F9FF",
  whiteColor: "white",
  blackColor: "black",
  grayColor: "gray",
  lightGrayColor: "#ccc",
  /* Stage Colors */
  maroonColor: "maroon",
  lightPinkColor: "lightpink",
  hotPinkColor: "hotpink",
  darkSalmonColor: "darksalmon",
  orangeColor: "orange",
  orangeredColor: "orangered",
  goldColor: "gold",
  yellowGreenColor: "yellowgreen",
  forestGreenColor: "forestgreen",
  oliveColor: "olive",
  darkSlateGrayColor: "darkslategray",
  turquoiseColor: "turquoise",
  skyBlueColor: "skyblue",
  deepSkyBlueColor: "deepskyblue",
  steelBlueColor: "steelblue",
  meduimBlueColor: "mediumblue",
  darkNavyColor: "#00143d",
  slateBlueColor: "slateblue",
  purpleColor: "purple",
  indigoColor: "indigo",
  slateGrayColor: "slategray",
};
