export default {
  primaryColor: "#666CE4",
  backgroundColor: "#F5F9FF",
  whiteColor: "white",
  blackColor: "black",
  grayColor: "gray",
  lightGrayColor: "#ccc",
  /* Stage Colors */
  maroonColor: "maroon",
  lightPinkColor: "lightpink",
  darkSalmonColor: "darksalmon",
  goldColor: "gold",
  limeColor: "lime",
  oliveColor: "olive",
  darkSlateGrayColor: "darkslategray",
  skyBlueColor: "skyblue",
  meduimBlueColor: "mediumblue",
  purpleColor: "purple",
  lavenderColor: "lavender",
  darkGrayColor: "darkgray",
};
