const twoMulTwo = [
  require("../../assets/images/dog1.png"),
  require("../../assets/images/dog2.png"),
  require("../../assets/images/dog1.png"),
  require("../../assets/images/dog2.png"),
];

const threeMulThree = [
  require("../../assets/images/dog1.png"),
  require("../../assets/images/dog2.png"),
  require("../../assets/images/dog3.png"),
  require("../../assets/images/dog4.png"),
  require("../../assets/images/dog1.png"),
  require("../../assets/images/dog2.png"),
  require("../../assets/images/dog3.png"),
  require("../../assets/images/dog4.png"),
  require("../../assets/images/bomb.png"),
];

const fourMulFour = [
  require("../../assets/images/dog1.png"),
  require("../../assets/images/dog2.png"),
  require("../../assets/images/dog3.png"),
  require("../../assets/images/dog4.png"),
  require("../../assets/images/dog5.png"),
  require("../../assets/images/dog6.png"),
  require("../../assets/images/dog7.png"),
  require("../../assets/images/bomb.png"),
  require("../../assets/images/dog1.png"),
  require("../../assets/images/dog2.png"),
  require("../../assets/images/dog3.png"),
  require("../../assets/images/dog4.png"),
  require("../../assets/images/dog5.png"),
  require("../../assets/images/dog6.png"),
  require("../../assets/images/dog7.png"),
  require("../../assets/images/bomb.png"),
];

const fiveMulFive = [
  require("../../assets/images/dog1.png"),
  require("../../assets/images/dog2.png"),
  require("../../assets/images/dog3.png"),
  require("../../assets/images/dog4.png"),
  require("../../assets/images/dog5.png"),
  require("../../assets/images/dog6.png"),
  require("../../assets/images/dog7.png"),
  require("../../assets/images/dog8.png"),
  require("../../assets/images/dog9.png"),
  require("../../assets/images/dog10.png"),
  require("../../assets/images/dog11.png"),
  require("../../assets/images/dog12.png"),
  require("../../assets/images/dog13.png"),
  require("../../assets/images/dog14.png"),
  require("../../assets/images/dog15.png"),
  require("../../assets/images/dog16.png"),
  require("../../assets/images/dog1.png"),
  require("../../assets/images/dog2.png"),
  require("../../assets/images/dog3.png"),
  require("../../assets/images/dog4.png"),
  require("../../assets/images/dog5.png"),
  require("../../assets/images/dog6.png"),
  require("../../assets/images/dog7.png"),
  require("../../assets/images/dog8.png"),
  require("../../assets/images/dog9.png"),
];

const sixMulSix = [
  require("../../assets/images/dog1.png"),
  require("../../assets/images/dog2.png"),
  require("../../assets/images/dog3.png"),
  require("../../assets/images/dog4.png"),
  require("../../assets/images/dog5.png"),
  require("../../assets/images/dog6.png"),
  require("../../assets/images/dog7.png"),
  require("../../assets/images/dog8.png"),
  require("../../assets/images/dog9.png"),
  require("../../assets/images/dog10.png"),
  require("../../assets/images/dog11.png"),
  require("../../assets/images/dog12.png"),
  require("../../assets/images/dog13.png"),
  require("../../assets/images/dog14.png"),
  require("../../assets/images/dog15.png"),
  require("../../assets/images/dog16.png"),
  require("../../assets/images/dog1.png"),
  require("../../assets/images/dog2.png"),
  require("../../assets/images/dog3.png"),
  require("../../assets/images/dog4.png"),
  require("../../assets/images/dog5.png"),
  require("../../assets/images/dog6.png"),
  require("../../assets/images/dog7.png"),
  require("../../assets/images/dog8.png"),
  require("../../assets/images/dog9.png"),
  require("../../assets/images/dog10.png"),
  require("../../assets/images/dog11.png"),
  require("../../assets/images/dog12.png"),
  require("../../assets/images/dog13.png"),
  require("../../assets/images/dog14.png"),
  require("../../assets/images/dog15.png"),
  require("../../assets/images/dog16.png"),
  require("../../assets/images/dog1.png"),
  require("../../assets/images/dog2.png"),
  require("../../assets/images/dog3.png"),
  require("../../assets/images/dog4.png"),
];

export const stageArray = {
  two: twoMulTwo,
  three: threeMulThree,
  four: fourMulFour,
  five: fiveMulFive,
  six: sixMulSix,
};

export const stageNumber = {
  two: 2,
  three: 3,
  four: 4,
  five: 5,
  six: 6,
};
